### ISSUE TITLE
get_xy_by_codeにおけるh_dec9の判定条件が異なる

### ISSUE THREAD

**Issue by hisaboh** [uncovertruth/py-geohex3#9]
geohex3.pyの283行目、

`    if h_dec9[0] in [1, 5] and h_dec9[1] in [1, 2, 5] and h_dec9[2] in [1, 2, 5]:`

の後ろ2つが、sa2daさんのjsの条件の逆になっています。

参考: js版の同等行

`	if(h_dec9.charAt(0).match(/[15]/)&&h_dec9.charAt(1).match(/[^125]/)&&h_dec9.charAt(2).match(/[^125]/)){
`

**Comment by key** [comment]
@hisaboh ご報告ありがとうございます。
再現可能なテストデータなどありますか？

**Comment by hisaboh** [comment]
それが用意できるとよかったんですが、そこまで追い切れていません。

**Comment by key** [comment]
@hisaboh 再現できたわけではないのですが、別の明らかなバグを発見したのでまとめて修正しました。python3対応がマージされたらpypi更新します。
